# docker-compose.yml

# https://docs.docker.com/compose/how-tos/environment-variables/variable-interpolation/

services:
  # docker compose run --rm rpi-image-gen
  rpi-image-gen:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEBIAN_VERSION: "trixie"
        RPI_IMAGE_GEN_VERSION: "master"
    image: rpi-image-gen:local
    container_name: rpi-image-gen
    privileged: true
    volumes:
      - ./target/${TARGET_FOLDER:?}:/workspace/build:ro
      - work-data:/workspace/work:rw
    command:
      - "build"
      - "-S"
      - "./build"
      - "-c"
      - "./build/config/${CONFIG_FILE:?}"
      - "-I"
      - "--"
      # Required
      - "IGconf_image_name=${IMAGE_NAME:?}"
      - "IGconf_device_hostname=${DEVICE_HOSTNAME:?}"
      - "IGconf_device_user1=${DEVICE_USERNAME:?}"
      - "IGconf_device_user1pass=${DEVICE_PASSWORD:?}"

volumes:
  work-data: