# https://raspberrypi.github.io/rpi-image-gen/layer/index.html

include:
  file: common.yaml

# https://raspberrypi.github.io/rpi-image-gen/layer/target-config.html
target:
  context: rpi3-slim-test
 
# https://raspberrypi.github.io/rpi-image-gen/layer/artefact-base.html
artefact:
  target_name: rpi3-slim-test.tgz