# METABEGIN
# X-Env-Layer-Name: rpi3-slim-base
# X-Env-Layer-Version: 1.0.0
# X-Env-Layer-Category: suite
# X-Env-Layer-Desc: Minimal Debian Trixie userland for the rpi3-slim target.
# X-Env-Layer-Requires: debian-trixie-arm64-slim,
#  rpi-debian-trixie,
#  rpi-misc-skel,
#  systemd-net-min,
#  systemd-timesyncd,
# METAEND
